# Generated by Django 4.2.16 on 2024-11-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_occasion_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='occasion_type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='occasion',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
