# Generated by Django 4.2.16 on 2024-11-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_timeslot_options_booking_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='occasion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
