# Generated by Django 4.2.16 on 2024-11-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_occasion_type_alter_booking_occasion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Occasion',
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
